### ISSUE TITLE
Setting opacity does not work as expected on feature layer if you set it with setStyle after some features have loaded

### ISSUE THREAD

**Issue by daniel-sabourin** [Esri/esri-leaflet-renderers#106] opened 2016-02-05 19:52 UTC
Hello again!

I'm having an issue with setting opacity after the layer has been added to the map. I add the feature layer, and then afterwards set the opacity with setStyle. The features that have loaded are using the published symbology w/ opacity, but new features to load use the default leaflet symbology w/ opacity. The expected behaviour is for all of the features to have the service defined symbology w/ opacity.

[Fiddle. Auto pan and set opacity after 3 seconds](http://jsfiddle.net/skoqkdu6/24/)

![Image](http://i.imgur.com/jwyI0oN.png)

**Comment by kneemer** [comment] 2016-02-09 03:31
I'm not sure what is going on here @daniel-sabourin, I [forked](http://jsfiddle.net/Lyew892r/3/) your fiddle and put in a different [feature service](http://services.arcgis.com/rOo16HdIMeOBI4Mb/arcgis/rest/services/continental_divide/FeatureServer/0) feature service and it works as expected. I chose one that had the same geometry type and renderer.  In your fiddle, if you put in another timeout and call resetStyle on the feature layer it goes back to the published symbology so for some reason it is being overwritten by setStyle instead of merging the styles.

**Comment by jgravois** [comment] 2016-02-09 18:16
@kneemer i loaded your fork a handful of times and i was able to repro reported error once there too.

**Comment by kneemer** [comment] 2016-02-09 20:52
@jgravois I saw the error just now when I first clicked on my fork but refreshed and now cannot reproduce.

**Comment by daniel-sabourin** [comment] 2016-02-10 19:39
The issue seems to occur whenever new features are downloaded after the opacity has been changed. The reason why your fiddle works most of the time is that all the features are downloaded before the opacity change occurs.

Another [fiddle](http://jsfiddle.net/skoqkdu6/25/) with another service, this time with polygons

**Comment by kneemer** [comment] 2016-02-10 21:14
It does appear that way.  Currently, all the renderer does is define the style function for the feature layer after the layer is initialized and the esri-leaflet plugin handles it after that. It does not hook into any other events.  This may have to be resolved in the esri-leaflet plugin, the style is there it is just not being applied when the new features download. I updated your polygon [fiddle](http://jsfiddle.net/skoqkdu6/28/) to reset the style and reapply the opacity after the features are downloaded and it gets the proper styles.

**Comment by daniel-sabourin** [comment] 2016-02-16 20:37
If this has to be solved in esri-leaflet, should I create an issue over there?

**Comment by jgravois** [comment] 2016-02-16 21:13
> should I create an issue over there?

let's continue trying to identify a repo case here first.  when i remove renderers from the equation and just define one style in the constructor and another later, i don't see the problem.

[fiddle](http://jsfiddle.net/gah2sghk/)

**Comment by kneemer** [comment] 2016-02-16 21:18
@jgravois, I reproduced with your fiddle by setting more than opacity on the constructor style,  [updated fiddle](http://jsfiddle.net/gah2sghk/1/)

**Comment by daniel-sabourin** [comment] 2016-02-16 22:03
My workaround right now has been to call resetStyle() and setStyle() on FeatureLayer load. It's not ideal, but it works.

[fiddle](http://jsfiddle.net/gah2sghk/2/)

**Comment by jgravois** [comment] 2016-02-16 22:24
> I reproduced with your fiddle by setting more than opacity...

thanks for this.  it helped me remember that we don't mixin individual properties when someone calls `setStyle()`.  we overwrite the renderer completely.  because of this, its up to @daniel-sabourin to provide *all* the appropriate style info himself.

what seems lacking at the moment is a public property/method on `L.esri.featureLayer()` to retrieve the current `style`.  y'all agree?

**Comment by daniel-sabourin** [comment] 2016-02-16 23:14
If I'm required to provide all style information myself, I should be able to get the currently applied style. That way I can merge in opacity and call setStyle.

Something as simple as getStyle() should suffice.

**Comment by jgravois** [comment] 2016-02-17 00:41
> Something as simple as getStyle() should suffice.

in esri-leaflet core you can already use `fl.options.style`.

in renderers, we swap in a more complex [function](https://github.com/Esri/esri-leaflet-renderers/blob/master/src/Renderers/Renderer.js#L88-L107) to do our 'mixing in'.

let me and @kneemer chew a bit.  we'll figure something out.

**Comment by kneemer** [comment] 2016-02-17 18:50
@daniel-sabourin, @jgravois, renderers binds a style function to fl.options.style so it will be available on the feature layer once it is initialized. It is possible to have a style function just using esri-leaflet as well [example](http://esri.github.io/esri-leaflet/examples/styling-feature-layer-polygons.html).


 I updated the both fiddles with the following function to read styles and update opacity on it, [with renderer plugin](http://jsfiddle.net/skoqkdu6/29/) and [just esri-leaflet](http://jsfiddle.net/gah2sghk/3/)
```
function setLayerOpacity(layer, opacity){
  if (fl.options.style) {
    var combinedStyle = (typeof fl.options.style === 'function') ? fl.options.style() : fl.options.style;      	
    combinedStyle.opacity = opacity;
    fl.setStyle(combinedStyle) 
  }
}
```
Two things to note:
1) Calling this function before the layer is fully initialized will result in no change to the style because fl.options.style will be undefined
2) The function above will only work for simple renderers, if you have a unique value or class break renderer you would need to pass a feature into the style function.

**Comment by jgravois** [comment] 2016-02-17 19:19
i like this.  
just a note, it is necessary to set `fillOpacity` if you want partially transparent polygons.

**Comment by daniel-sabourin** [comment] 2016-02-17 21:45
@kneemer This looks like a pretty good solution. Just a note for your solution, you forgot to rename your variables to use `layer`, instead of `fl`

**Comment by kneemer** [comment] 2016-02-17 22:02
Thanks for the feedback @daniel-sabourin, I've updated the comment and fiddles to use the `layer` parameter instead of `fl`.

**Comment by jgravois** [comment] 2016-02-17 22:23
okay.  closing, but happy to chat more if anyone has any questions.

**Closed by jgravois** 2016-02-17 22:23 UTC
